# Generated by Django 6.0.1 on 2026-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electeur',
            name='genre',
            field=models.CharField(choices=[('Homme', 'male'), ('Femme', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='a_vote',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='est_eligible_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
