# Generated by Django 6.0.1 on 2026-01-27 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0002_electeur_date_naiss_electeur_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donnee.election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donnee.election'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'electeur')},
        ),
    ]
