# Generated by Django 6.0.1 on 2026-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0003_election_alter_vote_id_candidat_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='filiere',
            field=models.CharField(default=None, max_length=75),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom_complet',
            field=models.CharField(max_length=200),
        ),
    ]
