# Generated by Django 6.0.1 on 2026-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0004_candidat_filiere_alter_candidat_nom_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='filiere',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
    ]
