# Generated by Django 6.0.1 on 2026-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0005_alter_candidat_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='filiere',
            field=models.CharField(blank=True, default=None, max_length=75, null=True),
        ),
    ]
