# Generated by Django 6.0.1 on 2026-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0006_alter_candidat_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='nom_complet',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
