# Generated by Django 6.0.1 on 2026-01-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnee', '0007_alter_candidat_nom_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnee.election'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='filiere',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom_complet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidat/'),
        ),
    ]
